spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: passwd
mybatis:
  mapper-locations: classpath:mapper/*.xml